version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - cp dist/server.js server.js
artifacts:
  files:
    - "server.js"
    - "node_modules/**/*"
